### ISSUE TITLE
How to use the trained model

### ISSUE THREAD

**Issue by prpankajsingh** [supasorn/synthesizing_obama_network_training#1]
Hi, Thanks for sharing this awesome peace of work. I trained the model with the data you provided using following command:
`python run.py --save_dir ./saveme`
Now, I want to test this using my voice. How should I run the code ?

**Comment by ghtwht** [comment]
self.audioinput = len(self.args.input2)
    if (self.audioinput):
      self.args.input = self.args.input2

    if len(self.args.input):
      self.test()
    else:
      self.train()

just give the value of input2

**Comment by linksyncjameshwartlopez** [comment]
Hi @prpankajsingh  have you got what you need?

**Comment by prpankajsingh** [comment]
Yes, thanks @ghtwht  .
